<?php

/**
 * Implementation of hook_menu()
 */
function less_blocks_menu() {

  $items['admin/settings/less-blocks'] = array(
    'title' => 'Less blocks settings',
    'page callback' => 'drupal_get_form',
		'page arguments' => array('less_blocks_settings_form'),
    'access arguments' => array('administer less blocks'),
    'type' => MENU_NORMAL_ITEM,
  );

  return $items;
}

/**
 * Implementation of hook_perm().
 */
function less_blocks_perm() {
	return array('administer less blocks');
}

/**
 * Settings form callback
 */
function less_blocks_settings_form() {
	$block_info = array();
  foreach (module_implements('block') as $module) {
    $module_blocks = module_invoke($module, 'block', 'list');
    if ($module_blocks) {
      foreach ($module_blocks as $delta => $info) {
        $block_info["{$module}_{$delta}"] = $info;
      }
    }
  }

  $options = array();
  foreach ($block_info as $bid => $info) {
    $options[$bid] = $info['info'].' ['.l(t('Edit'), 'admin/build/block/configure/'.$bid).']';
  }
  asort($options);

  $form['less_blocks_keys'] = array(
    '#type' => 'checkboxes',
    '#options' => $options,
    '#default_value' => variable_get('less_blocks_keys', array()),
  );
	
	return system_settings_form($form);
}

/**
 * Implementation of hook_form_alter()
 */
function less_blocks_form_alter(&$form, &$form_state, $form_id) {
	if ($form_id === 'block_admin_display_form') {
		$keys = variable_get('less_blocks_keys', array());
		if (count($keys)) {
			foreach ($keys as $key) {
				unset($form[$key]);
			}
		}		
	}
}
