<?php

/**
 * Implementation of hook_menu()
 */
function less_blocks_menu() {

  $items['admin/settings/less-blocks'] = array(
    'title' => 'Less blocks settings',
    'page callback' => 'drupal_get_form',
		'page arguments' => array('less_blocks_settings_form'),
    'access arguments' => array('administer less blocks'),
    'type' => MENU_NORMAL_ITEM,
  );
  $items['admin/build/block/less-blocks'] = array(
    'title' => 'Less blocks settings',
    'page callback' => 'drupal_get_form',
 		'page arguments' => array('less_blocks_settings_form'),
    'access arguments' => array('administer less blocks'),
    'type' => MENU_LOCAL_TASK,
  );

  return $items;
}

/**
 * Implementation of hook_perm().
 */
function less_blocks_perm() {
	return array('administer less blocks');
}

/**
 * Settings form callback
 */
function less_blocks_settings_form() {
  $form['help'] = array(
    '#value' => t('Configure which blocks should be hidden from the block list.'),
  );

	$block_info = array();
  foreach (module_implements('block') as $module) {
    $module_blocks = module_invoke($module, 'block', 'list');
    if ($module_blocks) {
      foreach ($module_blocks as $delta => $info) {
        $block_info["{$module}_{$delta}"] = $info;
      }
    }
  }

  $options = array();
  foreach ($block_info as $bid => $info) {
    $options[$bid] = '';
    $form[$bid]['name'] = array('#value' => check_plain($info['info']));
    $form[$bid]['edit'] = array('#value' => l(t('Edit'), 'admin/build/block/configure/'.$bid));   
  }

  $form['less_blocks_keys'] = array(
    '#type' => 'checkboxes',
    '#options' => $options,
    '#default_value' => variable_get('less_blocks_keys', array()),
  );

  $form['submit'] = array(
    '#type' => 'submit',
    '#value' => t('Save')
  );
  $form['cancel'] = array(
    '#type' => 'markup',
		'#value' => l(t('Cancel'), 'admin/build/block'),
	);
  
	return $form;
}

function less_blocks_settings_form_submit($form_id, $form_state) {
  variable_set('less_blocks_keys', $form_state['values']['less_blocks_keys']);
  drupal_set_message(t('Less blocks settings are saved.'));
}

/**
 * Implementation of hook_form_alter()
 */
function less_blocks_form_alter(&$form, &$form_state, $form_id) {
	if ($form_id === 'block_admin_display_form') {
		$keys = variable_get('less_blocks_keys', array());
		if (count($keys)) {
			foreach ($keys as $key) {
				unset($form[$key]);
			}
		}		
	}
}

/**
 * Implementation of hook_theme().
 */
function less_blocks_theme() {
  return array(
    'less_blocks_settings_form' => array('arguments' => array('form' => NULL),),
  );
}

function theme_less_blocks_settings_form($form) {
  $rows = array();

  foreach(element_children($form) as $key) {
    $row = array();
    if (isset($form[$key]['name'])) {
      $checkbox = drupal_render($form['less_blocks_keys'][$key]);
      $row[] = array('data' => $checkbox, 'class' => 'checkbox');
      $row[] = drupal_render($form[$key]['name']);
      $row[] = drupal_render($form[$key]['edit']);
      $rows[] = $row;
    }    
  }

  $header = array();
  $header[] = array('data' => t('Hidden'),  'class' => 'checkbox');
  $header[] = array('data' => t('Block name'));
  $header[] = array('data' => t('Actions'));

  $output = drupal_render($form['help']);
  $output .= theme('table', $header, $rows);
  $output .= drupal_render($form);
  return $output;
}